### ISSUE TITLE
Latest release failing due to no xcode 13 support on github

### ISSUE THREAD

**Issue by Reedyuk** [Reedyuk/blue-falcon#85]
Waiting for github to support xcode 13 - blocking the release

**Comment by nilskasseckert** [comment]
Hi @Reedyuk,
Anything new on that?
Regards,
Nils

**Comment by Reedyuk** [comment]
Fixed, being published as we speak, should take a few hours to be able to fetch v0.10.0

**Comment by nilskasseckert** [comment]
Hi @Reedyuk,

the new version can be still not found. Can you please check again?
Thanks!

**Comment by Reedyuk** [comment]
https://mvnrepository.com/artifact/dev.bluefalcon/blue-falcon/0.10.0

**Comment by nilskasseckert** [comment]
It seems that something else is wrong. If I use it on my KMM-Project. Version 0.9.5 is found and autocompletion works. If I now update to 0.10.0 the import is not found anymore.

**Comment by Reedyuk** [comment]
does the project build?

**Comment by nilskasseckert** [comment]
No because he can not found the lib

**Comment by Reedyuk** [comment]
is the samples failing to build when bumping to 0.10.0?

**Comment by nilskasseckert** [comment]
The sample application does not work at all anymore for me. Too old versions. Next week I can try to get it running but should be the same problem.

**Comment by Reedyuk** [comment]
if i get time over the weekend, i will try and update the samples for you.

**Comment by Reedyuk** [comment]
i have made a change to the lib to bump to 1.6.20 of kotlin.
I was able to get blue falcon running on 0.10.0 though.
I would recommend looking for version 0.10.1 and see if you have the same issue.
<img width="783" alt="Screenshot 2022-04-08 at 20 01 29" src="https://user-images.githubusercontent.com/3853006/162525292-7b3ed32e-a772-4c46-ab4b-aea62dbf2437.png">

**Comment by nilskasseckert** [comment]
Thanks a lot for the fast answer! It works now.

I updated the gradle version and some small things in Xcode for the iOS Project. Without the new gradle version the project does not build for me.

I openend a PR: https://github.com/Reedyuk/blue-falcon/pull/88 

Thanks a lot!

**Comment by nilskasseckert** [comment]
Version 0.10.1 works also for me. Thanks

**Comment by Reedyuk** [comment]
Just incase anyone else has a similar issue, blue falcon does not publish the x64 target because using intel ios simulator is pointless due to no support for bluetooth
